version: "2"
services:
#  varnish:
#    image: meanbee/magento2-varnish:latest
#    environment:
#      - VIRTUAL_HOST=magento2.docker
#      - VIRTUAL_PORT=80
#      - HTTPS_METHOD=noredirect
#    ports:
#      - 80
#    links:
#      - web

  web:
    image: meanbee/magento2-nginx:1.9
    ports:
      - "10.254.254.254:80:80"
      - "10.254.254.254:443:443"
    links:
      - fpm
      - db
      - mailhog
      - redis
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect

  fpm:
    hostname: fpm.magento2.docker
    image: meanbee/magento2-php:7.1-fpm
    ports:
      - "10.254.254.254:9000:9000"
    links:
      - db
      - mailhog
      - redis
    volumes_from:
      - appdata
    env_file:
      - ./global.env

  db:
    image: mariadb:10
    ports:
      - "10.254.254.254:3306:3306"
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh

  cli:
    hostname: cli.magento2.docker
    image: meanbee/magento2-php:7.1-cli
    links:
      - db
      - mailhog
      - redis
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento2ee.docker/
      - M2SETUP_SECURE_BASE_URL=https://magento2ee.docker/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=kliment.ognianov@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=qwe123!@#
      - M2SETUP_VERSION=2.1.*
      - M2SETUP_USE_SAMPLE_DATA=true

  cron:
    image: meanbee/magento2-php:7.1-cli
    hostname: magento2-cron.docker
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - appdata
    links:
      - db
      - mailhog
      - redis
    env_file:
      - ./global.env      
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "10.254.254.254:1025:1025"
      - "10.254.254.254:8025:8025"

  appdata:
    image: tianon/true
    volumes:
      - ./magento:/var/www/magento

  redis:
    image: redis:alpine
    ports:
      - "10.254.254.254:6379:6379"
    tty: true

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql
